services:
  db:
    image: postgres:16-alpine
    container_name: ${DB_HOSTNAME}
    environment:
      POSTGRES_DB: ${DB_DBNAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:${DB_PORT}"
    volumes:
      # - ./db-init:/docker-entrypoint-initdb.d:ro,Z
      - filmatrix_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DBNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      # Se monta el código en tiempo real, elimina necesidad de rebuild por cambio en el código
      - ./public:/var/www/html/public:ro
      - ./views:/var/www/html/views:ro
    environment:
      - APP_ENV=development
    depends_on:
      db:
        condition: service_healthy
volumes:
  filmatrix_postgres:
